In [57]:
import random as rnd

alphabet = "abcdefghijklmnopqrstuvwxyz"
alphabet = list(alphabet)
input = "yessir"
chars = list(input)
pos = rnd.randint(0,len(chars)-1)

temp = chars[pos]
if pos==len(chars)-1:
    chars[pos]=chars[pos-1]
    chars[pos-1]=temp
else:
    chars[pos]=chars[pos+1]
    chars[pos+1]=temp
print("".join(chars))

ysesir

In [79]:
def augment(df):
    data = []
    alphabet = list("abcdefghijklmnopqrstuvwxyz")
    seed = rnd.randint(0,4)
    for sample, label in df.values:
        data.append((sample,label))
        chars = list(sample)
        pos = rnd.randint(0,len(chars)-1)
        if seed ==0: #random deletion
            chars.remove(chars[pos])
        elif seed ==1: #random insertion
            chars.insert(pos, rnd.choice(alphabet))
        elif seed==2: #random swap
            temp = chars[pos]
            if pos==len(chars)-1:
                chars[pos]=chars[pos-1]
                chars[pos-1]=temp
            else:
                chars[pos]=chars[pos+1]
                chars[pos+1]=temp
        elif seed==3: #scramble
            rnd.shuffle(chars)
        elif seed==4: #random replacement
            char = rnd.choice(alphabet)
            chars[pos]=char
        data.append(("".join(chars),label))
    return pd.DataFrame(data)

import pandas as pd

df = pd.read_csv('datasets/confirmations.csv')
new_df = pd.DataFrame(augment(df))
data = new_df[0].values
labels = new_df[1].values
print(data)
print(labels)
print(df.columns.values)

['right' 'rgiht' 'correct' 'corretc' 'yes' 'yse' 'true' 'rtue' 'certainly'
 'cetrainly' 'good' 'godo' 'fine' 'fnie' 'yep' 'ype' 'yeah' 'yeha' 'ye'
 'ey' 'ok' 'ko' 'sure' 'usre' 'go ahead' 'og ahead' 'exactly' 'exaclty'
 'okay' 'koay' 'yup' 'ypu' 'ya' 'ay' 'of course' 'of ocurse' 'absolutely'
 'asbolutely' 'indeed' 'ineded' 'confirm' 'conifrm' 'definitely'
 'definiteyl' 'alright' 'alrgiht' 'why not' 'why nto' 'perfect' 'perfetc'
 'please' 'plesae' 'thanks' 'htanks' 'do' 'od' 'cancel' 'canecl' 'stop'
 'tsop' 'abort' 'abrot' 'disregard' 'disreagrd' 'forget' 'ofrget'
 'nevermind' 'neverimnd' 'end' 'edn' 'no' 'on' 'incorrect' 'incorrect'
 'wrong' 'wrnog' 'disagree' 'disagree' 'na' 'an' 'never' 'nevre' 'nah'
 'nha' 'nope' 'onpe' 'not' 'nto' 'false' 'fasle']
['yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes'
 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes'
 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes'
 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes'
 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'cancel' 'cancel'
 'cancel' 'cancel' 'cancel' 'cancel' 'cancel' 'cancel' 'cancel' 'cancel'
 'cancel' 'cancel' 'cancel' 'cancel' 'no' 'no' 'no' 'no' 'no' 'no' 'no'
 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no']
['Utterance' 'Intent']

In [81]:
import pandas as pd

df = pd.read_csv('datasets/intents.csv')

In [ ]:
import pandas as pd, nltk, joblib, os
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.metrics.pairwise import cosine_similarity

df = pd.read_csv('datasets/qanda.csv')
docs = set(df['Doc'])
dict = 
for doc in docs:
    questions = df[df['Doc']==doc]['Id'].values
    dict[doc]=questions

print(len(dict))
print(len(df))

1194
1473

In [13]:
from datetime import datetime
start = datetime(2020,10,3,5,40,50)

In [27]:
age = datetime.now()-start
print(round(age.days/365),"years", age.days-round(age.days/365)*365,"days")
print(age.days)

4 years 54 days
1514

In [76]:
import nltk,re
from nltk.tokenize import sent_tokenize
input = "i like to eat oranges and apples, but i think i'd prefer to munch on a banana. what do you like to eat?"
clauses = re.split(r'[,.!?]|(?:,\s)?(?:but|however|although|because)',input)
clauses = [clause.strip() for clause in clauses if clause.strip()]
print(clauses)

['i like to eat oranges and apples', "i think i'd prefer to munch on a banana", 'what do you like to eat']

In [117]:
import numpy as np
df.loc[0]=['what is your name?','bot']
df

                  Utterance    Intent
0        what is your name?       bot
1                     howdy  greeting
2                        hi  greeting
3                      hiya  greeting
4                       hey  greeting
..                      ...       ...
59  do you have suggestions  discover
60           your abilities  discover
61        your capabilities  discover
62               your scope  discover
63           your abilities  discover

[64 rows x 2 columns]

In [143]:
text = "when was i born?"

pattern = r"(?P<name>(?:name|called|call))|(?P<age>(?:age|old))|(?P<birthday>(?:birthday|born))"
matches = re.finditer(pattern,text)

for match in matches:
    for g,m in match.groupdict().items():
        if m:
            print(g)

birthday

In [ ]:
import re
texts = ['i want to see coldplay in march']
pattern = r'''
((?:(?:can )?i('d|'ll)?(?: will| would (?:like )?| want| like)?(?: to)?(?: see)?)?\s*
(?P<music>(\w+\s*)+)?
(?:(?:can i (?:go|book))?(?:on )?the)?\s*
(?P<day>\b([0-2]?[0-9]|3[01]|[A-Za-z]+))?(?:st|nd|rd|th|\b)
\s*(?:of |/|`.|-)?\s*
(?P<month>\b(0?[1-9]|1[0-2]|[A-Za-z]+)\b)?
\s*(?:in |/|`.|-)?\s*
(?P<year>\b\d2,4\b)?)'''
for t in texts:
    match = re.search(pattern,t.lower(), re.IGNORECASE | re.VERBOSE)
    print(match.group('music'),match.group('day'),match.group('month'),match.group('year'))

want to see coldplay in march None None None

In [374]:
import re
texts = ['january','jan','1','12','20']
pattern = r"\b([A-Za-z]+|0?[1-9]|1[12])\b"
for t in texts:
    match = re.search(pattern,t.lower(), re.IGNORECASE | re.VERBOSE)
    if match:
        print(int(match.group()))

ValueError: invalid literal for int() with base 10: 'january'

In [331]:
import re
texts = ['can i see From First to Last','i want to see Coldplay', "i'll see coldplay",'Sleep Token','Fever333', 'i want to go on the 3rd of march',"i'll see From First to Last on the 5th of march 2025",'the 1st of april','A Day To Rememeber']

for t in texts:
    match = re.search(pattern,t.lower(), re.IGNORECASE | re.VERBOSE)
    if match:
        music = match.group('music')
        day = match.group('day')
        month = match.group('month')
        year = match.group('year')
        print(t)
        print("music: ",music.strip() if music else None)
        print("date: ",day.strip() if day else None,month.strip() if month else None,year.strip() if year else None,'\n')
    else: print("no match: ",t)

can i see From First to Last
music:  from first to last
date:  None None None

i want to see Coldplay
music:  coldplay
date:  None None None

i'll see coldplay
music:  coldplay
date:  None None None

Sleep Token
music:  sleep token
date:  None None None

Fever333
music:  fever333
date:  None None None

i want to go on the 3rd of march
music:  None
date:  3 march None

i'll see From First to Last on the 5th of march 2025
music:  from first to last
date:  5 march 2025

the 1st of april
music:  the 1st of april
date:  None None None

A Day To Rememeber
music:  a day to rememeber
date:  None None None

In [556]:
m=r'''(?:.*?\b(i|we)(?:'d|'ll|\b)\s*(?:will|would(?:\slike)?|want|like)?\s*(?:to\s*)?(?:go\s*(?:to\s*)?)?(?:see)?\s*)?
(?P<music>.*?(?=on|$|in))?'''
d=r'''(?:.*?\b(?:go|book)?\s*(?:on\s*)?(?:the\s*)?)?
(?P<day>(?!in)\b([0-2]?[0-9]|3[01]|[A-Za-z]+))?(?:st|nd|rd|th)?\s*
(?:of|/|`.|-|in)?\s*
(?P<month>\b(0?[1-9]|1[0-2]|[A-Za-z]+)\b)?\s*
(?:in|/|`.|-)?\s*
(?P<year>\b\d2,4\b)?'''
l=r'''(?:.*?(?:in|to|around)?)?\s*
(?P<location>([A-Za-z]+)+?)?'''
t=r'''
    (?P<type>
            (?P<standing>
                ((stand(ing)?|stood(?:\s*up)?|floor|pit|general|crowd|arena)\s*)
            )
            |
            (?P<seated>
                ((seat(ed|ing)?|s[ia]t(ting)?|reserved|allocated|assigned|chair(s)?|tier(ed)?)\s*)
            )
    )'''

texts = ["sitting tickets"]

for s in texts:
    match = re.search(t,s.lower(), re.IGNORECASE | re.VERBOSE)
    if match:
        t = match.group('type')
        print("t: ",t.strip() if t else None)
    else: print("no match: ",t)

t:  sitting

In [557]:

t=r'''(?P<VIP>(VIP|premium|back\s*stage|special|yes))|
        (?P<general>(normal|nothing|regular|general|no))'''

texts = ["special"]

for s in texts:
    match = re.search(t,s.lower(), re.IGNORECASE | re.VERBOSE)
    if match:
        t = match.groupdict()
        print("type: ",t if t else None)
    else: print("no match: ",s)

type:  {'VIP': 'special', 'general': None}

In [558]:
from dateutil import parser

date = "1 2 24"
date2 = parser.parse(date,fuzzy=True,dayfirst=True)
print(date2.day)

1

In [559]:
now =datetime.now()
18-now.hour

10

In [575]:
from collections import deque, namedtuple
d=deque([('VIP',1),('general admission',4),('number',3),('location',4),('date',5),('artist',6)],maxlen=6)
print(all([item[1] for item in d]))

True

In [634]:
import pandas as pd
import statistics
df = pd.read_csv('datasets/music_genre.csv')
df=df.dropna()
df['artists'] = df['artists'].apply(lambda x: x.split(';'))


individual_artists = set()
for a in df['artists'].values:
    for art in a:
        individual_artists.add(art)
individual_artists
df

,artists,album_name,track_name,danceability,energy,track_genre
0,[Gen Hoshino],Comedy,Comedy,0.676,0.4610,acoustic
1,[Ben Woodward],Ghost (Acoustic),Ghost - Acoustic,0.420,0.1660,acoustic
2,"[Ingrid Michaelson, ZAYN]",To Begin Again,To Begin Again,0.438,0.3590,acoustic
3,[Kina Grannis],Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,0.266,0.0596,acoustic
4,[Chord Overstreet],Hold On,Hold On,0.618,0.4430,acoustic
...,...,...,...,...,...,...
113995,[Rainy Lullaby],#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,0.172,0.2350,world-music
113996,[Rainy Lullaby],#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,0.174,0.1170,world-music
113997,[Cesária Evora],Best Of,Miss Perfumado,0.629,0.3290,world-music
113998,[Michael W. Smith],Change Your World,Friends,0.587,0.5060,world-music
113999,[Cesária Evora],Miss Perfumado,Barbincor,0.526,0.4870,world-music

In [650]:
import statistics

artist_genre={}
for artist in individual_artists:
    modal_genre = statistics.mode(df[df['artists'].apply(lambda x: artist in x)]['track_genre'].values)
    artist_genre[artist.lower()]=modal_genre.lower()

In [660]:
import joblib
genre_df = pd.DataFrame(artist_genre.items(), columns=['artist','genre'])
genre_df
joblib.dump(genre_df,'music/genre_df.joblib')

['music/genre_df.joblib']

In [688]:
import joblib
df = joblib.load('music/genre_df.joblib')
print(len(set(df['artist'])))
genres=['alt-rock','alternative','black-metal','bluegrass','blues','classical','country','dance','death-metal','deep-house','disco','drum-and-bass','dubstep','edm','electro','electronic','emo','folk','funk','garage','goth','grindcore','grunge','hard-rock','hardcore','hardstyle','heavy-metal','hip-hop','house','indie','indie-pop','jazz','metal','metalcore','pop','progressive-house','psych-rock','punk','punk-rock','r-n-b','reggae','reggaeton','rock','rock-n-roll','rockability','singer-songwriter','ska','soul','techno','trance']
artists = df[df['genre'].apply(lambda x: x in genres)]['artist'].values
print(len(artists))

a=[]
a.append('bob')
a

29812
11399

['bob']

In [2]:
import joblib
df = joblib.load('music/genre_df.joblib')
len(set(df['genre'].values))
len(set(df['artist'].values))

29812

In [ ]:
date = datetime(2025,6,1).__str__()
print(date)
new_date = datetime.strptime(date[:10],'%Y-%m-%d')

2025-06-01 00:00:00

In [676]:

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer

stem = WordNetLemmatizer()
text = word_tokenize('how are you doing?')
text2 = word_tokenize('how do you do?')

print(" ".join([stem.lemmatize(t) for t in text]))
print(" ".join([stem.lemmatize(t) for t in text2]))

how are you doing ?
how do you do ?

In [51]:
from datetime import datetime
from dateutil import parser
pattern=r'''(?:.*\b(?:go|book)?\s*(?:on\s*)?(?:the\s*(?:one\s*in\s*)?)?)?
(?P<day>(?!in)\b([0-2]?[0-9]|3[01])(?:st|nd|rd|th|/b))?\s*
(?:of|/|`.|-|in)?\s*
(?P<month>\b(0?[1-9]|1[0-2]|[A-Za-z]+)\b)?\s*
(?:in|/|`.|-)?\s*
(?P<year>\b\d{2,4}\b)?'''
t='the one in feb 2025'
match = re.search(pattern,t.lower(), re.IGNORECASE | re.VERBOSE)
date=''
if match:
    for group in match.groupdict():
        if match.group(group):
            date+=f'{match.group(group)} '
    print(parser.parse(date,fuzzy=True,dayfirst=True).__str__())

ParserError: String does not contain a date:

In [41]:
import re
pattern=r'''(?:.*?(?:like|some|see|go\s*to(?:\s*see)?)\s*(?:.*?(?:some))?\s*)?
            ((?P<genre>.*?)(?=\s*music)|(?P<music>.*?)(?=$))'''

texts=['i like heavy metal','rock music','hip-hop music','pop',"i'd like to find some metal music",'i want to go to see Sleep Token']
for t in texts:
    match = re.search(pattern,t.lower(), re.IGNORECASE | re.VERBOSE)
    if match:
        print(match.group('music'))
        print(match.group('genre'))

heavy metal
None
None
rock
None
hip-hop
pop
None
None
metal
sleep token
None

In [46]:
df= joblib.load('music/genre_df.joblib')
df.tail()

              artist              genre
29808           zeus             brazil
29809         avatar        death-metal
29810  the berzerker          grindcore
29811    emancipator           trip-hop
29812    Sleep Token  Progressive Metal

In [79]:
import random
random.seed(3)
x=random.randint(0,10)
y=random.randint(0,5)
print(x,y)

3 4

In [133]:
from nltk.corpus import wordnet
import random as rnd, string
def synonym_set(text):
    augments = [text]
    rnd.seed(42)
    words = text.split()
    #replace with 3 synonyms
    for _ in range(3):
        for word in words:
            synonyms = set()
            for syn in wordnet.synsets(word):
                for lemma in syn.lemmas():
                    #ensures replacement
                    if lemma.name()!=word:
                        synonyms.add(lemma.name())
            synonyms=list(synonyms)
            #replace the word
            if synonyms:
                augments.append(text.replace(word,rnd.choice(synonyms)))
    return augments
chars = list('word')
aug_chars=chars
aug_chars.insert(rnd.randint(0,len(chars)),rnd.choice(string.ascii_letters))
aug_word = "".join(aug_chars)
print(aug_word)

wozrd

In [147]:
now = datetime.now()
now.strftime('%Y')

NameError: name 'datetime' is not defined

In [165]:
z=['a','b','b','f','f']
a=['g','f','g','j','d']
#del zip
zzz=zip(z,a)
for zed,ay in list(zzz):
    print(zed,ay)

a g
b f
b g
f j
f d

In [17]:
import re
from dateutil import parser

text = "the one in april"
pattern=r'''(?:.*?\b(?:go|book)?\s*(?:on\s*)?(?:the\s*(?:one\s*in\s*)?)?)?
(?P<day>(?!in)\b([0-2]?[0-9]|3[01])(?:st|nd|rd|th|/b))?\s*
(?:of|/|`.|-|in)?\s*
(?P<month>\b(0?[1-9]|1[0-2]|[A-Za-z]+)\b)?\s*
(?:in|/|`.|-)?\s*
(?P<year>\b\d{2,4}\b)?'''
match = re.search(pattern,text, re.IGNORECASE | re.VERBOSE)
date=''
if match:
    for group in match.groupdict():
        if match.group(group):
            date+=f'{match.group(group)} '
print(parser.parse(date,fuzzy=True,dayfirst=True).__str__()[5:10])

04-15